using System.Drawing;

namespace WalkerSim.Viewer
{
    internal static class ColorTable
    {
        public static System.Drawing.Color[] Colors =
        {
            Color.White,
            Color.Red,
            Color.Cyan,
            Color.Yellow,
            Color.Blue,
            Color.Green,
            Color.Magenta,
            Color.Lime,
            Color.Navy,
            Color.Orange,
            Color.Purple,
            Color.Aqua,
            Color.Maroon,
            Color.Gray,
            Color.Pink,
            Color.Gold,
            Color.Violet,
            Color.Turquoise,
            Color.Olive,
            Color.DarkOrange,
            Color.MediumSpringGreen,
            Color.Brown,
            Color.RoyalBlue,
            Color.Chartreuse,
            Color.Tomato,
            Color.SkyBlue,
            Color.Indigo,
            Color.Coral,
            Color.DarkRed,
            Color.LightSeaGreen,
            Color.OrangeRed,
            Color.SaddleBrown,
            Color.LightPink,
            Color.MediumVioletRed,
            Color.SpringGreen,
            Color.DarkOrchid,
            Color.Tan,
            Color.DarkGreen,
            Color.Lavender,
            Color.DarkBlue,
            Color.Orange,
            Color.HotPink,
            Color.ForestGreen,
            Color.MidnightBlue,
            Color.LightYellow,
            Color.DarkViolet,
            Color.DarkSlateBlue,
            Color.PowderBlue,
            Color.Goldenrod,
            Color.Teal,
            Color.DarkMagenta,
            Color.MediumTurquoise,
            Color.Fuchsia,
            Color.Beige,
            Color.DarkCyan,
            Color.LightCoral,
            Color.AliceBlue,
            Color.Crimson,
            Color.LightSlateGray,
            Color.Sienna,
            Color.LightSkyBlue,
            Color.MistyRose,
            Color.BlanchedAlmond,
            Color.MediumBlue,
            Color.SandyBrown,
            Color.DeepSkyBlue,
            Color.CadetBlue,
            Color.AntiqueWhite,
            Color.Peru,
            Color.PaleVioletRed,
            Color.MediumAquamarine,
            Color.Bisque,
            Color.RosyBrown,
            Color.CornflowerBlue,
            Color.LemonChiffon,
            Color.MediumOrchid,
            Color.DarkSeaGreen,
            Color.LawnGreen,
            Color.DarkGoldenrod,
            Color.Aquamarine,
            Color.DarkSlateGray,
            Color.FloralWhite,
            Color.LavenderBlush,
            Color.DeepPink,
            Color.Snow,
            Color.GhostWhite,
            Color.BurlyWood,
            Color.DarkGray,
            Color.MediumPurple,
            Color.Wheat,
            Color.NavajoWhite,
            Color.DarkKhaki,
            Color.Salmon,
            Color.SeaGreen,
            Color.PeachPuff,
            Color.Moccasin,
            Color.PaleGreen,
            Color.LightBlue,
            Color.Cornsilk,
            Color.Thistle,
            Color.LightGoldenrodYellow,
            Color.MintCream,
            Color.PapayaWhip,
            Color.LightSteelBlue,
            Color.Azure,
            Color.Gainsboro,
            Color.LightGray,
            Color.LightCyan,
            Color.Ivory,
            Color.LightGreen,
            Color.IndianRed,
            Color.SlateBlue,
            Color.LightSalmon,
            Color.OldLace,
            Color.MediumSeaGreen,
            Color.DodgerBlue,
            Color.DarkOliveGreen,
            Color.PaleTurquoise,
            Color.SteelBlue,
            Color.YellowGreen,
            Color.SeaShell,
            Color.PaleGoldenrod,
            Color.Silver,
            Color.Honeydew,
            Color.OliveDrab,
            Color.Khaki,
            Color.RoyalBlue,
            Color.Firebrick,
            Color.Violet,
            Color.SlateGray,
            Color.MediumOrchid,
            Color.DarkOrange,
            Color.Crimson,
            Color.RosyBrown,
            Color.RoyalBlue,
            Color.Cornsilk,
            Color.Coral,
            Color.Azure,
        };

        static ColorTable()
        {
#if false
            // Shuffle the table.
            var prng = new Random(1);
            for (int i = 0; i < Colors.Length; i++)
            {
                var idx1 = prng.Next(Colors.Length);
                var idx2 = prng.Next(Colors.Length);
                var temp = Colors[idx1];
                Colors[idx1] = Colors[idx2];
                Colors[idx2] = temp;
            }
#endif
        }

        public static Color GetColorForIndex(int index)
        {
            return Colors[index % Colors.Length];
        }
    }
}
